import test from 'node:test'; import assert from 'node:assert/strict'; import {answerService} from '../src/services/query/answer.service.js';
test('custom owner and hidden folder meaning produce correct evidenced count',async()=>{const r=await answerService.answer('acme-law','How many open deals does Garima own?');assert.equal(r.status,'ANSWERED');assert.equal(r.answer.value,2);assert.deepEqual(r.evidence.matchedRecordIds,['D-101','D-102']);});
test('dead folder overrides stale active status',async()=>{const r=await answerService.answer('acme-law','How many lost deals does Garima own?');assert.equal(r.answer.value,1);assert.deepEqual(r.evidence.matchedRecordIds,['D-103']);});
test('unknown owner yields verified zero rather than hallucinated answer',async()=>{const r=await answerService.answer('acme-law','How many open deals does Priya own?');assert.equal(r.status,'VERIFIED_ZERO');assert.equal(r.answer.value,0);});
test('cross-source filing evidence is merged and verified',async()=>{const r=await answerService.answer('acme-law',"Was ABC Pvt Ltd's income tax filing filed last month?");assert.equal(r.status,'ANSWERED');assert.equal(r.answer.value,true);assert.ok(r.evidence.matchedRecordIds.includes('F-201'));assert.ok(r.evidence.matchedRecordIds.includes('G-301'));});
test('CRM filed state without acknowledgement is surfaced as conflict',async()=>{const r=await answerService.answer('acme-law',"Was Cedar Works' income tax filing filed last month?");assert.equal(r.status,'CONFLICT');});
test('same engine compiles a different client schema',async()=>{const r=await answerService.answer('northstar','How many open deals does Garima own?');assert.equal(r.answer.value,1);assert.equal(r.semanticMap.entities.deal.ownerCandidates[0].field,'Relationship Manager');});
test('every numeric answer carries record evidence',async()=>{const r=await answerService.answer('acme-law','How many active tasks does Meera own?');assert.equal(r.answer.value,r.evidence.matchedRecordIds.length);assert.ok(r.evidence.matchedRecordIds.length>0);});
test('misspelled owner is never silently dropped from the query',async()=>{const r=await answerService.answer('acme-law','how many open delas garims ownn');assert.equal(r.status,'NEEDS_CLARIFICATION');assert.equal(r.answer,null);});
